### PR TITLE
Fix login mechanism using mobile API endpoint

### PR DESCRIPTION
**Pull request by joaonmatos**
When logging into SIGARRA to scrape course units and schedules, we were going to the main page and logging in using the form.

However, that page now features a hidden redirect that stopped our spiders from correctly checking that we signed in.

To mitigate this, we now log in via an endpoint in the mobile API.

### CODE REVIEW

**Comment by miguelpduarte** [comment]
To simplify potential later debugging can we just include the status code in the failure print?
Other than that, looks good!

**Comment by joaonmatos** [comment]
I have since discovered that the login endpoint returns 200 even when the credentials are wrong 🙄 and will dealing with that.
Don't merge just yet

**Comment by joaonmatos** [comment]
At the moment if the auth fails, the script shuts down as expected. However, it does not print the error message for some reason. I have even set the flush flag to True, to no effect. @miguelpduarte, do you have any idea as to how this behaviour would emerge?

**Review by andrefmrocha — APPROVED** [review]
I went ahead and filed the issue. Let's leave it as is for now

**Pull request merged**
